travis:
  secure:
    BINSTAR_TOKEN: ZoU52k7Wb4UPW9IPhZ+3jMfQLlNXskDYtZySxs66QoU3ul+rFRnPsy4n6ITdVW4Vxv+tQrTqPX4JlEeSHcbTqxF9bpUHdUpXt4koWN8pCSR+rwfIICtLfukgd9YxupJ8mBS7EW9TlBvSbv0bZaHE0/TrtFYXwgeKAMm6E3Xq3RuIINM5URyBFgviRnEUPL0QsD6rXItDbWnDlxg1GpJO2lSVPpPeFeKGqnxzeRgk+4O7uX1+I7EyeaifhB1JrVap55xWOrms0tCgSJr2IBiDAIM6y03Jr4L60SuQNsCP71cJveJMcnjWnXVstpIN9LNn3Gt+Y851j7DuCkmEoNoJDHkSL2XqcPiHhY9A8XZnxCx2VozxxgqE/eoEkm4tVJqSdiQKzVZLKhX0XkExxFTfQpCOms4MdWJOv6wjv7oko6ECIOCAQISM+HBu5ZqV+BjGhSRhBGP7Lg8R5p1hCwTK/6rTFJJEtJj0WXEo6A7EspePctkVAgEDyXtkkyGtSTSqPJ//RmtIzAWs1b5teKHan417tLaqqi9ja2/cs21TgZmmY0CdC/RDZPA9BamOBI07gqr/VmPqBuzsu6rFbtoTSczrf5fR/rOAC++M7l6YuoAAq+jnUQFVktbfGebi/aQrrKBSgJvvfW4GT7nHgvmMKesvEkTMZCzx0G58VnKyGIk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
