travis:
  secure:
    BINSTAR_TOKEN: KH2WzsvNox62AkjBAHm0tdsw/ZmgA4aHhO2lwt+w6/ldBE+HF8b+teNQiG8dR7XcB3ukNzqKXbKl1CjRpXNUXbT8SQpsmLpLqQ+2r2SEBrg5xXTgRcOag5uX7zloectwJtBgzH5sbq2QEJx0KTTkgNq22MamHUNssBz5pzeCR28msB1i8uRH4/lusP/mSVefKoKEcfmNqHJWmi6yeLuuv2ZWDLyp0Ve2iu1oQxglG+V44809bn98CpU0z6oxS81bRudAOAFd5AWh+kXUkQw5bbgWNI4SLkv8H05GLeiezMK2h3PMXbYiibMN1aIJiMVIAlJzpVqcu8nNzapaDXIejKBETR0vkdE8Dguw0iLF2ptPIZ0qPbsQ57sUUw4YyocJoa+7fcKUYKMz7TAoWUa4+DyTWnx0PvuXT/YrUyPkjQVT+syUMaWxkC9UL85OOBZ5V2Ba84iLiT6W1s/0TPwsEuGTR2mcAWGkHFW8g1LDWzvby+8qxL2yOJ0VnvOUZZood+abWSjGxJblWq/ZQUyKDptjb0dDZ8PjVU906PKbMsefiM9kIUYtPT75Ao7AKKswaVcUlocBUGuSucm0bXz/6zX4t/0b/KYdqrgztAtVNAAPPTN4Ica5NJGEPeDkHrpQMNbL/HYI89lIPUcn5WSni1mo4Wfmi2H97lizfOf6f48=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
