travis:
  secure:
    BINSTAR_TOKEN: VGTS54Jw229Ic95bpGNwfn5xV17OjhTEdzcfSOfOx2q9fRzPXLyFz2V4SBN1isEM47aw3O31Mt7pJNDh0ONEkB0+efUSHoOvlmaxTRe++N9fwXj6k1mnNNEnDyM7tyMkCVGCiQZIw/2wsGuLtk6ju3mX0aZhtVOnxLRmP7oD/2vQW+jP7gbF8FGgxv7kd1T//cqLW05pR3rACWjz110BMiODmD0LWKFEn3fYUqApPnj5UnBXoCQxKw5U2aw9pV8x/Ny6om0+FQF9ZxCDT3JOur5tFspFIHo2lWNbB4K/o18iTav2gPMbdCRs2HBFE/4oJ0Y+coKPiUfyyMKCfKxylUNuUFJb357phZiNm/qz7aJGuaDS1WDNyAWnhApbEBOkib71uNampWiRiqwRkp3XJzLaO0L3t6OxrxG+YfSNghAzjcfCmLv4EO+jfDaSu4wNl4tG+Q3XGJXET/wjoDsE4El5jlOijwYByJak8oPqXotbOY0H3bXvJWxspIJKI3QQa52fcuNer8ZjX+61MY8t469F3MywmZM8936j58Qt6N/8EnkMjjogYXJoIPWEbpku5GQnt0IWwUZQBOqRj2HPdolBBJle5yFgV/7wGA4vnTr0W9S4Qt8jDKCcPorXJQV+CaPsYiE1zOQ1iW/yYvuK6kqd0BXvwWjTwfmOIHv2eI4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
