travis:
  secure:
    BINSTAR_TOKEN: akkZ3xRCfN8UW19g9WIRB5r8iochIqmaKzKeOO4AnLjsXsOxaNdoh5MwnNviLamHxySv4aYvvZmv+D8V2j9rwgQwf+uDHITYhWFJX5WZ4tNB1xbKhAQojmVdSx4HRm2pKQRHyU1zP/VqNgwVuPL9hiGooAcjyt4JvGpZWF0Dwi2hXc/vEW42hNlazCOkQXSzuRIr1hdzST2efnp8Bq0teE6MZPjQgNU84u9i73ysHLiLVrDzmY832NDsGRZtwelv86p20CMkBh1vX96rchloS2X+UkRNuzHQakIFUAZ/sjaeRglFMtBE9C2bpwlOO6dQTXPZB39KZSEXiJZYqtcOKjJuV6/In5NJOhpGXZN60yPeQqUFF4i+c+jCCciQ8r2OpPA3xvCrQ5Dv4x3io3A7PzjTNFwrnlkRZKOM12ocH4wow3XbnhIfbRnchH58K/BOLXkTISymQdaUl/mpZq470dGdxRxHC+Ojfi24sd33ZFbJtcidF7grJgr/ecYonz9sFM8HSBag8ETIkfBTmy+9XKyW9GeL4tmKfkFbGdLehyRIHSLN1bnVw8cZU6RUTWx1vyXDGGvZWrDuRD0nMyVis7Kqd1UDxD1OVtFqbEBLCihJ+UVUew8gUAI7Hd+I+GXvDNyN3rmM5Q7oFD7IJVZZjP4+d0voicEZwGWd1XXGd3M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
