travis:
  secure:
    BINSTAR_TOKEN: ZYlVY45Yj3F524/45TeS66OrIXRpRcRzgYrF2goSW67Vn7gcvDBcqcD3n1SbAByqtlDd8Z7+RcSOLH6PGguGZm3AqTqjw1K36zW8jfBuihUG7UTrajKfm24HytMZfvC095VaCiuPsY+smtTdXbbTuduA9ynM2E34SCM/5ayvg4KJ7W8F7jFRqqkyxDh3DUZ3Ge+GbttuVEs03b6JaPSdspwip/Da5NOfFGbIbsF3cIXPUAEJSlrL0dzjJM2I7P3BulV9jc4jP3BTtSH0GpNGb+HWndzZrL6mvsv5bd8zn+ev1PEJtoRB39MQaxhe3wzk3tUB+KWNK5OQMMWgom9zSDEHa303aZ55L2zyLEAZhzSo8wTM0Fh47SbQmGF2NwWRVDVHM9kr6UvQvr3nUiI01jwLGVDJ1h8CQehnndTMZccK95HH13R0vwKiz55WNYniBLfSs2bDeJBrZeNNlxK+1OBUBjK84bR1uc59sgnvelxP3F0jb2YEWSujw+N02ldGXAv/ovpY+P81rQ2TYiqAExwe087NiZvmTvkUbBxUQ3z47xRtfGYjAmXGaEJURhr5MmoYPKdLuN1eNrO5HtRu3b0OI/AJXwJrWSKEcBN7mXaCY1c1w9C5Y6qEPvFnLKxH3wdKEjinYwj0MW6yyHciUTYspYq+kLMjFo6Uz5k1q3I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
