travis:
  secure:
    BINSTAR_TOKEN: YyMVaOr0eZ2ciNyAVRN+j9kqlIs+rzxM/mdN33yzuDwc3mSM+89L9TMp3Pxw0EM1eEPOVBrvH/t04tk21ISUIysBC0eeLhuiv5wNebqMnISg9bQj4AFC4MTiZEDWUYIPw/dtgk+pJG2w6d75hbLd2WUW6bYCWlEkjAKxwJwgviSHUK6lv36lrR5kFuadJf1voiejdwBMZttgZwqHR35muGxr1KQkBjP6JMlo9a6auyqFENPL4m5ckbvtGcH1mYdagJo1pOGJSOEUqPgzdbfhAc9OcCuRdWIoy6jTQIQEGG/i5lMak1HermE6nsz4npnIs2fSqTKenkXKdVD3Zc+7Jk+8gfZbNWaOqL629BxO47y9Mm5ljUMN38d3rrrUilDGF6eO/Fu+w/o4mETE9a0G58W+zE4cqRJcBLZmyAUZUsBhOj5kqDokRpcDr961jzYT+jeo4HaGiq+KViHDDXdiyUkKksfxdK6SwBWn8D9Dl1hek8JgtfwQ2tPBJrj6U42B7VOr/qhMLl4J9xK/ukKaM4iaBy/Ik7dfdFvz4eAcZATlUV2DalkIi3e+g9kwU8dOih23DeCKXoSTk/ty+a2qkbAFXI/JHesqXxquIOoC1EB7vE8AEATLCdoJsNnL3eRHEusC3eBnHR9JJtZ9fRXcEFzNMKqIovOgnRVW/IEj6Fo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
