travis:
  secure:
    BINSTAR_TOKEN: LHDSzlpJYy0Wr8hhUK2chujXxDgBoOqXf0G/dnlR3bSRy0GMJiWNytg4sGHM7IBTZJu32J9SzYoq9hAA9KBQHligUYDQUOtxmiE/PjTVRWB0zBkXghWNwIz/uqAOsd6t4k1a5hTxQNhMbQV+NNWlSV8TXjbTtChIpy37cl0GLcT4Oh4v39Yl6mC/zmsjeNKclQ+T9PTsu87EWDtvzphkVG2A0TI/pldue2sY/xuguvlToGiqqhBycLGdtRHwNqlo2+DO9piIclx2XX1Hw4kEMYLg8jMIfy8EPy3Vf4f78jl6hcbm8RXOaeQNWL3x9wFhlGdzBeBw0PXlL2kj3iyZ3iU9hA5/DRLXD9LUb1ydBCuJei0d0z2KQR60PER9Wr8fYcnumkXk5ijAj2eP9q4SmK5D8SymkCQ6RxYuj9HCbmvLJ2BBvG/hFiXuhxbxyLtfnTJ2w5b7gKYiwo0SEEJPrQ0u0CdEK+LWekLCMTvErO68UnqIjdsKMDS5nEgJ7B8xoc7NNRLc1WBqTSsUp4zCBMAxwWAESrBe2XZnl1zLMlITfS5HFFCgz9HGJ7k1d8bpVeKPhCrRQnHQNdvpPWhsRT+knZzgZG+brmlHaSwqxcOzL50ebBFgpXpr7p9YuXkXHw98pTVRb3i8BYUSaxKsqjMOY+xrM996pZDoGI1+u68=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
