travis:
  secure:
    BINSTAR_TOKEN: b2zVM/Rw+MKJgAH08ZcVX0cwx/GmPfQKKDMAGkVMZBv0eFWEFlB8YgeXLfGTcU0x6Sl5dagI579cODXkayYOWHozTp8fgu5qXd+/G8INnSKX3S/HJaMxJQucQRAoxrrfHn+4dtDZKU5MvChNS7jnMvMSI+GgJkiVNJp9mF0BIxf7vNhHmZay5rmB1JmgIYkNGJJ0C/dvOiAwVnv7Ef7ggH/X8C7O4o0sCidU0m0CRBmtYa1xmRZE2XYXKiJEGELLEmkUxq6waoWANtzdtU2NubVvgqEsAmEZ0Hn3e9tGaEWHaCuvvsmhq42dydC2ZcqqpapPaKnL82rBwdxh/UaUYQ2pbAWYwrdEOlfQZCRic4crezaXTcxiZpNb3+DGngfkwNtSGeRj34EPUKAC3FT5bkpoxhWf6aDz7hxSx2LkNl2gzDbo0ywx3hylKUVnI1+CjyNYSmiVc6V9C49HvkXkolvOofOY669clAewituNtBVzeefnFXC9bdar5rdAfzDtakHfu5BqaaG2j+MAsiDSERNOWuGrGEw9Jh+bUHIfQwavAGTyCAFwa6s7UPsRljua6BFhB95qmiZVH254I0KTEHELOcmjssHSTw53/ssEDZ4KV+dIh+EvdP24x2etoZhitNRURyt+43OM7HhLex6QkTkbTyjzacvVtREXkL3YJ/k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
