travis:
  secure:
    BINSTAR_TOKEN: kOixpZarhwg2O8Kmhr4zcw5WRWvJtIGKfODq/a2+nCGP2wMS0lRMcKcjrcmwxKWPGcPJMiSS8odNPTe8fGKwQ0p1pwdjUKHydBm/m4rWBoJhm0CvXF8O6OFpNT8oSNrvyMSbDSPkdk0SpOxAJtFZqqT3s5NLaNfbxJ7+TTZchSfbL0bhZ9SgDGs9r70y94SYF6ke4DdKcegEIogsq6Ii7tOqGNlWaBolMVegJcXDAWggL2MKojPfZQGoFl4kIDAfAxYchmotDhpsH9RnRiBOXOZTlOX03PI1iSiyI1ElVmWaNrs+/hnQB3mte25wskS4SJdTEsjNchAWdN0SXwzYDYHUalHsod9MjngeECKRlM0k/HoOAyrheGt7ETOC3OCN3nX7rIAlkOtaN3WvQRg4uKpOXU/1/lqBTT7JXR0kW73Ps+7ICBwI9AjVR7Q4lD0DbXABC8FVHhjkzBorxdW4YoCBPt3GZeSFqTryTY8fskbwMkAECl4cYjHNntajjxldqm+ICyNNTwVbGNIRj3gP6UVb13Lh8Wi4ghI1PI6k1gHuoEHVE4FdXlNyiNdw1NJoNje/OOsesvkTyimizMXbd8ZLuOZyWegkS0BqURgDMFmpIwnpz9L28NTQJEh3ORPhvOpCRPen/I9liK0CSmq2AbILlrrY8Zvdsko313B/SbM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
