travis:
  secure:
    BINSTAR_TOKEN: HXTbYkWGfogR2BnDI8fcjDnTaUD/DYo4OE5tVLSpVHDT6I8XPwf4Pe0ceRvtlLGBr6Zo3rS/5ba8Vd4i0SUWm55FsL0jmvMwMawp5Fhpwubd1pVFjY7pin9R5wo/3fv6m3XSLP3xZpAgX/YzyBUXfR53vVRWuUUlnKJmIwI5hd1DV4m884hs12TYqq1YOasE0kgjsbxXiQJ0FjcOIs7Etx3Cn4mWYBNJwQyHub1RDcXXcKSaqahwiBaG7+ds3NGIoCVLcRxRo5Rd7BvbHXtSIw7YbPL7rPuZD7z0vjpiIkc4fW+lAILWIae7oUcDDiQaK152hAvZQjfiQ4/8l5mSmLbpytNVU9FvE9924x/D3Csept/TKJg8ojIY2QG0FxClGZfvWeCKncxbbcadgU5Djw5JlCtdZ9BVgXcOHoSD6/DzVvzaDiT35Z4kZPSSVezJDPu/2JMe/FS+9FthGXLiQHmEahAhByaNXyDsw12BMGQB2T+KeJOF7ybdga3JjjS30b41hnRYveDNWDsVDTsWvahW3/mDywJAWAcAC884KxBwEqCG//n+EpPOOBvZhsM5P/ihsBq2oYQXhdnUV+1jEf4EU1N6VOsauhzb0urwPSSIu42M1ExEFWHfdApcJLqa2T3pcIqZ72iuC1y58/i38+tHqj0R7+uzdzSAkxN8Dwk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
