travis:
  secure:
    BINSTAR_TOKEN: MXtoZ43+zzF1uoBLyBJjGGq13A2qoDtOO053PmT16/Br9vAlVnBH5qzvWkCzXSyKateRtErIxRDjVTN2LigbU3GZBrLDaGfZIaBfshyyINgcPWZJApfl5iLIQZH92LdEzCFyKlIAie87TiJRYXBYm4lGMP6Hd2mEKLKZsvzslArQBoR9quTTlJCMxFQq4foWg1XHDkXs6xeJmUVqp+Tj1jv2H6OIeYIYNlmlwsv4d2HADONB/oUwxB505Yvo+NRv4orC6dbsZ5PxP6KQsC4liLhsZBcQlU9pTd3OssxEocaoUY5FNf/XkNlG+FdlsyMz7ULzQd8fDOfS2wNKnZM3y+oDuixjDfV0U6dx8tzuZbELyhtr//oo2Cvko++EYnjPzDbD3KNJTHQK1b8jb+GtgafGgtOZaU9AnTPgaqXR3QtKI6XuBCREdZZ7q8hQZvSLYpXULeQEkImpAckyGmwsPcoY8v30ZJ2SHFNosrTDdEG8oPqZ95N6DIYCK6JdPt/hr5pWfnETkvp4EJerPW8hMonSEBy1iJjEljs+rs+y/hJimhd8MtF0iFxe0bpsL7YPJ1PqxW3NCWepYEAOFg/bjCXkHoCSwrIb7lQeXzbwN7lw7aAQvr+7LyZwJD5oEHpMBJDhBbBoRq1Vl/wgNSZtIRqfZLMsHYixvxxpctmAKE4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
