travis:
  secure:
    BINSTAR_TOKEN: VNU1y08qWNvGq/mM9gqorJVxWwubw63vJpmVfObwMgpx0DH2EVXZBMjVPz6U3TQHIYNuxUtUkz+qnl8hh4hy3D5wI0Ta1mK+bfb3DQbu+YDvhmmAiosPj/g1TbiRJUkCb6NI2KwaiMUVte0HmG+lKAWPjin5uSNHP0wGSVmC/mPH19Uu5PSW87/Lpx+TgMfl6LtHZyRebtu4IdPAPZgzgUfUZvZAxtNJeiHfMZdpHZKts7QyvubxwTM91bJ2kEo4NdXOBjuOXvAWpVDxzSLGyE0RTeWklX9v1TzMOUlyL94jkUxONveCM3Icwg0S9CxHxYDsAt2cCW/hpLHdH1SX3FeUsN5c8qu2iv8CpBh76OwC8p1VaCwv8wRkl1aZ3DxRw7bqWdYLdimTLxYRvd+uC8sy8iC4HPLXRECEyMF4vV6D5XvC/52IFVzU1m6Dn3QDVoSj0q3GradTNqcc19vI6YNgIJaZFtWWe8qQMVIzqvRa2UrBG7X31tKzKXy0Lc8dPg4Z2Q57AcfG7LfHnok5evVfJSH7CYNkOc7zWH82kNtwGOkaHJnNUb8+N1265EJGZXznnloAAkOM0SLWKhQzXa2b3wpwo4eu+t5GZ1fGti363Q0VTMRwsZXG7cy6ca2/auLkw/TdFSqsApR5qKjGdnJ7fH3GT8QMgIcYfO4jvY4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
