travis:
  secure:
    BINSTAR_TOKEN: WOEp6aieKh5mkxOjrg0WQYwDdZL8o7D3f4ilHH1YktG817y3a6p6AyGGoF0gCbYr5kG3VsKDKivpM9z1Blqi4JNYaRfoxKSBUysH3PFCluzlWEnIzY9z9wKoYaG6KuKUzC/f5Kl0AbBpEy//vUgfAPjkqhR3VwfbJmeMNGlRj/oVpZqTG1JyvgHzuuC311rD7c9qm9M5sc88CZHtfocRgCaFyCU25hzVwcTQwEdcAbm8fTy7dc8e+D/YkTFCWCRC5aRiQILWq4ixtZTWXq93pGOzsd7iLSZ+lchsMm3+XIxla5KRCFehgdnirnRmNI4s1QPdF00Xzqx9e/WeyIxjmMT8vSWzASLv02m3mijlM/hCzrNcWb1KncpHi+bJ6zBbIZbneRn84LNQwoq58TLIAweVYtn0ajyHidmgABqQoe1mfXxejVWKfGXwKATF66ohdXywI8H5Ai87g4hhYA69jd8eJNKnbj5kalIkq7iazI9Xb6Mrmy59/RdaXCX3UY9CoMJv/bGT5PmOkyczT9skFrFBivzUNxXNYHqWSIz84NgcIBtcDRLB6WYyf90H24H/Ilw7MgAc4xS+7k2U8kTBlUr347yn7H/3ZbHhXKsCEjOfKPDP0XTnNUW8TMIV8DJEzQWk0fZzbqS5e5a25Hq1kkK6q9N4U1lwkm4T/Qtm+CY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
