travis:
  secure:
    BINSTAR_TOKEN: oyPCWPHNZKDo7HFZRu8u32vGLLEn3EXn8ClNNMpHMRIM3Dy1yn8u0QN0k+m6u0iKOiKwOJkXvDt8nAq0KsZ0fHW9ZhnCV+AmtotiOWbdsTUeOgWRTK1GUmjPGbN6gmIUrfTerddCR2O/xiGFRU4yOiglBnhZZ8N83oVmMba3Y5BrpVYcvmVSpG9sHFBDRI4OSw7aCqH7G2rW28sapo36hZ0LBnRMPJXhhkY6w1UVWXEJNuBUx41S+VJUafwOl8doGSEA95Fz8Kf11rg8oY2KJFq/dk0JTjnYHBP9vXWwRK0DUW+SAsYsijNY0dbLLWFoQzPzEkdO///UB7o8ylK8jvlERn02W/dVpPAti7qbg+Xt/3taQWsZlxjWyBc2HuNkZ4JTOk9Lz9Vaxe8ye1dXjHrPF/8g4NZnseGQRXF/oufYiPB1vIJZ+UX91hpHWv9U94tM/mb3x4kzkDfhV3wKE0YQzGS79lmeUB9PYMIYuY8Rj21AK+CxaUSR8yljxk0EvLDQf6C49bNwmNvJ1G5N2gHor+DYc1N3A9D0oOAr6bysRVLAHFRkcndF35Gwo0yQ2zLLvjI2dQlz6m6AYU6tjKLtDVWTwAKbVZXqDMzWpOifnKzrQOY3r8NA+66bppSJZR9Z9bWIz1CnSWQl0VlgQcBimhbMkagD++iyzZPEfHc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
