travis:
  secure:
    BINSTAR_TOKEN: AaA/gC5MWK/seaH4I/5LFajtlzKgyFN7A1HtMz6neOjG5ntlA7mpfKxTTjvtQ8VuWAYYHPf/57i1S9NzHTDZEvgUo6ZtyQSvaQFuKrIC22A3rmkmiiXlQRGfIHXzdTJr4hfUxviA8CQcwBdurJ5YM8lBM22yWnBEwSlucT4tHqCF7HeF3EQgAvuWJdsgMfjEk0/BZANL5yTdv7vZO6kSZmjdYYNHQ1bF+wXN/hLg38ij9MRxpU2hj6GQDMQ5pKuYvI+NOUIn77rb2VCFd8apip77bOT0DNRRGmdfVcBuLg2gb1lAt6noiWYJL5LtWrX/3nm5QXLBphUAWffgTeOWWrt2hhxguBV/vbsGit269DdKvAEpmA/0aq2oYktzk0NevqJaaJwA4fi7m5IwAZu8Pg8D+SFA8JtIoqsxXjVn0Niq95+AAK9fL37RJnz+bTNgaVs7hSJO0TNVdCdG3+mHr+OzCQj/ppfzWcLHmmnl1PWR+qCYkBtg4omNIrRJGWjKBqN09eEMnDk1mPuWlWLf1pcJiD67hVY1KL8R82qsmTlxa+vohGDL9VvIjt4jtFcOfF2CBpaRU0Hxri6iQhbDwlAL+cmZer0gO+lEmmrf07lbJObuexMXwmleEOrw2uk3gXwlhmiHid99X8FVUuUKsFC9grs1Umxf++Qnu9sLuUI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
