travis:
  secure:
    BINSTAR_TOKEN: H5DROeW2fdfoKZh2oZSNb7jFyGaquhICtQUdqF0Ov1i44LrQapvS31QfgthiHY61TFdfdafbo2hugczmcPcffc8qr1VJB7jlHf96JODGJjV9w0JEwe+HfvI3PpWPpbQWO7lB0T8H4L2+Xa7G7M3zds4Fd7O1y+EB8otc7LNF7Lgb7FAZ87sv+gvmnI5JVeGnG61RY4ypaYN/MnxPhZer344bEkPUqdkcTS4N9jrikSTWjDFavwwU3Kjjfk/YJmRLe/1mhT2ewY1sp1w7yV403v4W59tsd0/e2PIZOOfE535O1jw7dks7kMK5VSZoDV7fvDatqxq9XBu+llJ+bPHuTz19yckw6NFLeezjUDKSUtP8CGxDxz5BiBhgk9c5E3vZGe7tUg1WAvQQ8lI/MciMG4VH0+G4ZVwCFuRWfS309+mn00h4zxoqbNoAy42YES+4Snx/zwWxh2rptxgTa47G6oX/Rp/5u+n7sNuAFPdoNC986ay+l+tbyVrLybJmgPBZxJayROcdRQHa5837beaEKV7pkJ3ZdJA5i52SHEDNLhQCh53JHPBZ9olh6aH7Ve2S3wcKaFGzKTAvmQqcOBhZKBZLKMhnADoXGaJiRNxAwutmTyNeCnNal8XLrleu3Y4+uRtpukRE1irsoRWRBxpFnjMbpNQ3NM/f3fdVArxn6lU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
