travis:
  secure:
    BINSTAR_TOKEN: HYCN95+EGxWCEImAUFD+AFMppC3hsYUvKcIFdF2JmoQIURXWFY/QseE9BZcF0DImVp3oRJNWlu5QMxOsC0JvzHx5EwgTLve96PmMMmw9JxR8oSw54IsM7UML3lKfVVLcsCGMRsAmGi++g3RoXSUt60tY52b2Q2wWrpbw2baZG7gl1NHReDCblmLbVD9YARXkfCgRs+AF6K2BDrowoyth1a6um+Axbh4IrgUHTUiO8JVKQRU8StH3C4lJd79zZSViPNtDCmL70n3fJExdkr5C62uQKnXMuz+d7g35zwSl5hXlQugA+1t3EV42NflvSbuBVfa3I7XLw0NxBR1qLKgt4dJsklM0RLD/tLzcyXYP7Gh4T8j8Is3An1ABxxFcarASc7K9u9ZoxAjYIXJ9UmU3rObu6UIlZKTTXoCcmCuIKWMiblZLYYqLxMX1XbuY2DXaeAIqICJYcI2JToQM1R/93GGt7lD03N0uFTdhUwO7a4AlpvbnxjXZk8pB5kGmqBraP1Z4ydHVmG0h14ePT3Ez2YSo2MZLOzJWtd6cyDkd0rYJbFFM08cSzNjJJmRG+/DUzJ+LzDa2W1IqHz4Fafadi+e8Y8gix2/MzXa2l+izU5eXYc+K0SDqPcMsvIJrq7OC0kQ7kF5nvxSef+p/fhViCp7BZz2Y9d2QZjyrc2Rh6bo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
