travis:
  secure:
    BINSTAR_TOKEN: kdjtT+KDGsGNmui74CUDPVPFc2Rghmrh8OCmQuEzyFmuSNKjl6jqiB0lwIHHtTrdx7a9nNDto7V02DAxQN0YfCsmAvq3lNe+VGMIV2xkDFfska33vgZnjbxvZ/QYzQ4QtdlI7YCEAhxMsx9MTPSu8FcBvXwTbo28okpKxV9O4Pu9qAuVADbdiD+zaftsinsXmkKzg6U6DkQ+raVADkkpydMhYqmJrzNPYcCGrcrEvxOD9fZw7bHVbTEcVzy4Ke7KAlCXpedP8VU5XiWxCSWiQyVIo8U1+zGLV6lRlybGHaRzEeZF73ExotGgdZhhDA0Zq2ntGcL3GRgBEHIc2txibRT7hxBoOLqABP73OVpDOOcKqM/4jIFdguzNFYwUqE7Rz8lRIqpGw63xr+aPlVhgL/L9DXoKiDGJ8Fb1kNrtOSFn9TvzYWqWnHZSkP/DxhNS8cmc52K7Y6FjgTPSARebISCF/1sDnqJ+le16atEUSps/se8eR59NwIn4R7/scawHmV9ecZttkxSV6NJE4lfC+RsUWXsRCFHYZQ6sIKl3VelN03oUzjfZcm+YsEEn+PJyzYc+XWCRCKGN2zg3CnhWFcpvS8FFhoPWofYZy6N0TlPfSotPy6zHMoiOVW4N/Gye6Yye33M1a3cHywVmBDakn3JUvssdUEXqJzrcUvJRWKE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
