travis:
  secure:
    BINSTAR_TOKEN: Ev3r9XAkvQTuLPU9itsBYm2WyMgQZXUQshUqYFGTp8d1ebB/83PkeiL6xdSDJynUYTY1399SMgy8DMsNBUCiNSE1PLtcy7Xzk31g0YHub1Q/Xjj/xRrdQYSXxwTCp7czWUP/87mjWmbRxf9yKDbY66UVCCuZwlXv6ufMzQUkVtNL/i7sBtEh58aRofNnfyxH2LcOPQ0IY4woBCjomObh5i0QPQsZ/H4BgKyLvuqZBUc7GTRHvv5yXstOsHhtiXP+oiBr0NO5lPxUD1ChYN8nxxnHeVaOI2J5bc5aQKg7a0HHLAjGKb9gi3JcIDIxZ0UQ9KhaPNLJqb5WQI1TKgxpFKTbyhy6fYTwfDRAnQfFyxfVtTLVOppVsH+ccGQwKF55wyE8ygFMKZRgQ3Gd0AUPEHLOOWYT4MqT39fxDL+S6iIHqNK3GAaTIewfhBo8TirEM6mcf/XXkDWt8VhiiYU00a9k0MolQXfAbSaWzS7aJ4Z4tYmunpXsrgnA70Z7+tWaOFiXK3sqwRFuEv+kstIEjYH7O9eJ6ijXKDhZSZaThO/ZEXNnED3UbFYk7V7ImHwYegWAsdlL3ABYJ/mv4zZsFYdLCM6u1vNbkNkJwGIsq2uko9+b/iSZj3LPv61Nno9RAmutpsOhvSePJE05+ABKsxyDxswpUnaCxHEjn40i/iM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
