travis:
  secure:
    BINSTAR_TOKEN: ceATQ/YCpSX21DU7CLLHvToMMxGejoinplBAdV3ZOJMbU52L+j2Dj1QnSzI+KyhpYqHZdLNCdaPXa0N14auAttTDEyYaBptt3p3OBxuqVLXEQfeDSbQyZsxMSs0hVde2HmabllCIfV7mdjny67FPfXjAPucuDNzJYJSCu8xaKIbojj2oBcGHpNmcX8u9fzhqCVbKFzxvLxC5EVqIxPaXCQLX7IinKmVveqTOaSeme70Ri8DCKhEtBMmN1F1q/EMghvT6PJLYQuMgC+id9Q/oI8yDneYjNdOe9XmKPDgISu5KFhDw9Flu/UEB5+4hDmkvj40KTfN3ytbGNsObhzzAJJ096ppJ7ig0eLk0kbeMgY3gAeyA9XwBP48aayj7w0s8NNh1tAc9X9qF2JeybTImd9qfDqXnt0DMvfHn7+SSKJYv2/vjrBv3g8AC09YzVP+vXlErhCpuaZ8fUD5RWg1Xd/H33VW4HTmQlgfCG/NzTHl5GZE4L7N1Uv3Vx3Ipxl64HfOo20C5ddF3snwiObZb6z8i178ZJ463XXgV5rUa9os+5VdOF1T4bjtk8sxiK6+zCUEO8O73c8amZNU5bBiOeC7msOTY45/5j1WKaRth2UVVswUbjP67ar4r/dIjDibi9VsLeB8TNYYQIFAvCbv2p7rnKMt18mGnvRTzYSANjNM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
