travis:
  secure:
    BINSTAR_TOKEN: Ky3Kpc/qXyL976GUrJXC4f9ewFwJidci6PCE85dU6YwuirWJOlRcg9EgfcV/DFojjyzpgCJktTF9WYMAY8O7aH3SnnzowpEi0SfnIBFOf7aMwcbOwn62a4InR8fs8u77kDGYyy2Hkv2JaunA3c9fZfmCC8tdyM3bKrWzfln8HGBK4MhQBP2w7HKbQk1qv9tavIucjvHrtTNsH1OesuoW/nndD8EVKM84c+rfrwi3ZJ1KMwehNmWrT4pBEr/hIHUpk2FRN54xN/+7YnbgLnVN8k6qKt4re0FEgtCZGmkIeSg4EI7lO04rdPQd8L1d22C6qKca2pRFeisu7SsSbjDGs8XXxqrPcXWC0QC+firaQonmq7mrdq1ClPEjG4YxkmjJpDfgC+i/scNr89+iKUmdveVyF0w8m//UzBtMNS5WjrY9UJQpXL/uofkFt/T/MBStXjczFhEnVU1MzQ0gAmrC5mwQupxUzPKFHtlDjtmoGbHWfcWXCATfY89q5NyWBYE0ClP4IH2q/hUWhJ8ujVUbc1+K++PoBkfYYArA8+FbW4D3cJpZYHf48haiVlb0Tp/fsoiDB+PDXvTX2v2Ibs54NJ8xGxrS25g6OT5Ie2jqO6VxWli6SOrZhd/idveTEBhzpS5m3xqo6DV2Ke2qxgp3EENy669q7r9jacYtHJ6cXJ0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
