travis:
  secure:
    BINSTAR_TOKEN: BakhhCnf+QPMAQZTBcpRRdGqfzAx8zZg0SbKZFKmCrZkCRcfnYWbP+F6UfvhVbg9MJN0hCRJp4IK81m0ckntF43WoaAfdiolZoPJOZsbZRSXl9S9d0lWdYdyReX+H1tUKZSvkYKH8xoGHI3n57VLpsPj9HapnD6WOpKpMuf3F90/h+U0anNfPS28Ze5DcSu3B57RbOvPdFQSP28q2tZUNzGcDYSHdfSdG9NT6QtqdEM3bezFwBgUENu2aBvuh6HoNPRDn7UFFmsHXrX/TJCiUi12DNNcXboj+pe9InbK79tV7340W7d/snDNdPvcmzyPhPlyc0/wIMtDQG0CKyL9uOvApWwzNJOHKdgSVrme3Lj5TyuvkajXB/hCcMUCidezlUURAr13Sowr8rn/2I8rd+1JgIrV4G/houPeFmACnJq2xVQIRwRC/JcP/NPa4u/rWmtLFNWHCMPxGg8lMTqeGtFCQj9HW8vrOpSRteuHtpn/Gq4j/9Ewy3fufJcMO4fRivYreLi8ywJazdAzYwA7pmT27d3nGsI8iqvlcwIXf36KOU/4gGLgbeOuogWKNL6VrafdUUezSak4PHErHJvkX9tlBMmFCXobse9WJ+3oLlFTVIXIZaSvTecBfNWvHczf9rbSIAkWPPuUSLnPFpZP2/cbJU7gD79aSvRygKrLxgA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
